-- 005_context_knowledge_overlay.sql
-- Agent-readable source knowledge plus a user-writable personal context overlay.
--
-- Source tables are generated by ingestion/extraction and are not writable by
-- normal users or MCP clients. Overlay tables are user-scoped and exist for
-- agent notes, preferences, and personalized higher-level concepts.

CREATE TABLE IF NOT EXISTS transcript_lines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    video_id UUID NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    start_seconds NUMERIC(10, 3) NOT NULL,
    end_seconds NUMERIC(10, 3) NOT NULL,
    source TEXT NOT NULL DEFAULT 'youtube_caption'
        CHECK (source IN (
            'youtube_manual_caption',
            'youtube_auto_caption',
            'youtube_caption',
            'generated_transcription',
            'imported_file'
        )),
    language TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS transcript_lines_video_time_idx
    ON transcript_lines(video_id, start_seconds);

CREATE TABLE IF NOT EXISTS source_concepts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    video_id UUID REFERENCES videos(id) ON DELETE CASCADE,
    concept_type TEXT NOT NULL DEFAULT 'concept'
        CHECK (concept_type IN (
            'concept',
            'claim',
            'method',
            'algorithm',
            'tool',
            'entity',
            'implementation_note',
            'pitfall'
        )),
    name TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS source_concepts_video_idx ON source_concepts(video_id);
CREATE INDEX IF NOT EXISTS source_concepts_name_idx ON source_concepts USING gin (to_tsvector('english', name || ' ' || summary));

CREATE TABLE IF NOT EXISTS source_edges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    video_id UUID REFERENCES videos(id) ON DELETE CASCADE,
    relation TEXT NOT NULL
        CHECK (relation IN (
            'explains',
            'depends_on',
            'contrasts_with',
            'implements',
            'mentions',
            'supports',
            'warns_about',
            'related_to'
        )),
    from_ref JSONB NOT NULL,
    to_ref JSONB NOT NULL,
    evidence_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS source_edges_video_idx ON source_edges(video_id);
CREATE INDEX IF NOT EXISTS source_edges_relation_idx ON source_edges(relation);

CREATE TABLE IF NOT EXISTS knowledge_artifacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    video_id UUID REFERENCES videos(id) ON DELETE CASCADE,
    artifact_type TEXT NOT NULL
        CHECK (artifact_type IN (
            'study_guide',
            'tldr',
            'concept_map',
            'agent_summary',
            'product_spec_context',
            'repo_match_summary'
        )),
    title TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT '',
    source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by TEXT NOT NULL DEFAULT 'system'
        CHECK (created_by IN ('system', 'user', 'agent')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS knowledge_artifacts_user_idx ON knowledge_artifacts(user_id);
CREATE INDEX IF NOT EXISTS knowledge_artifacts_video_type_idx
    ON knowledge_artifacts(video_id, artifact_type);

CREATE TABLE IF NOT EXISTS agent_notes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    tags TEXT[] NOT NULL DEFAULT '{}',
    created_by TEXT NOT NULL DEFAULT 'agent'
        CHECK (created_by IN ('user', 'agent')),
    created_by_client TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS agent_notes_user_created_idx
    ON agent_notes(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS agent_notes_tags_idx ON agent_notes USING gin (tags);

CREATE TABLE IF NOT EXISTS personal_concepts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    source_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'learning', 'applied', 'ignored', 'archived')),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by TEXT NOT NULL DEFAULT 'agent'
        CHECK (created_by IN ('user', 'agent')),
    created_by_client TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, name)
);

CREATE INDEX IF NOT EXISTS personal_concepts_user_idx ON personal_concepts(user_id);
CREATE INDEX IF NOT EXISTS personal_concepts_search_idx
    ON personal_concepts USING gin (to_tsvector('english', name || ' ' || summary));

CREATE TABLE IF NOT EXISTS personal_context_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    from_ref JSONB NOT NULL,
    to_ref JSONB NOT NULL,
    relation TEXT NOT NULL DEFAULT 'related_to',
    note TEXT NOT NULL DEFAULT '',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by TEXT NOT NULL DEFAULT 'agent'
        CHECK (created_by IN ('user', 'agent')),
    created_by_client TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS personal_context_links_user_idx
    ON personal_context_links(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS context_preferences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    source_ref JSONB NOT NULL,
    relevance TEXT NOT NULL
        CHECK (relevance IN ('high', 'medium', 'low', 'ignore')),
    reason TEXT NOT NULL DEFAULT '',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by TEXT NOT NULL DEFAULT 'agent'
        CHECK (created_by IN ('user', 'agent')),
    created_by_client TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS context_preferences_user_idx
    ON context_preferences(user_id, created_at DESC);

CREATE OR REPLACE FUNCTION touch_context_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS source_concepts_touch_updated_at ON source_concepts;
CREATE TRIGGER source_concepts_touch_updated_at
    BEFORE UPDATE ON source_concepts
    FOR EACH ROW EXECUTE FUNCTION touch_context_updated_at();

DROP TRIGGER IF EXISTS knowledge_artifacts_touch_updated_at ON knowledge_artifacts;
CREATE TRIGGER knowledge_artifacts_touch_updated_at
    BEFORE UPDATE ON knowledge_artifacts
    FOR EACH ROW EXECUTE FUNCTION touch_context_updated_at();

DROP TRIGGER IF EXISTS agent_notes_touch_updated_at ON agent_notes;
CREATE TRIGGER agent_notes_touch_updated_at
    BEFORE UPDATE ON agent_notes
    FOR EACH ROW EXECUTE FUNCTION touch_context_updated_at();

DROP TRIGGER IF EXISTS personal_concepts_touch_updated_at ON personal_concepts;
CREATE TRIGGER personal_concepts_touch_updated_at
    BEFORE UPDATE ON personal_concepts
    FOR EACH ROW EXECUTE FUNCTION touch_context_updated_at();

DROP TRIGGER IF EXISTS context_preferences_touch_updated_at ON context_preferences;
CREATE TRIGGER context_preferences_touch_updated_at
    BEFORE UPDATE ON context_preferences
    FOR EACH ROW EXECUTE FUNCTION touch_context_updated_at();

ALTER TABLE transcript_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_concepts ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_edges ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE personal_concepts ENABLE ROW LEVEL SECURITY;
ALTER TABLE personal_context_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE context_preferences ENABLE ROW LEVEL SECURITY;

CREATE POLICY transcript_lines_select ON transcript_lines
    FOR SELECT USING (
        EXISTS (
            SELECT 1
            FROM videos v
            JOIN user_channels uc ON uc.channel_id = v.channel_id
            WHERE v.id = transcript_lines.video_id
              AND uc.user_id = auth.uid()
        )
    );

CREATE POLICY source_concepts_select ON source_concepts
    FOR SELECT USING (
        video_id IS NULL OR EXISTS (
            SELECT 1
            FROM videos v
            JOIN user_channels uc ON uc.channel_id = v.channel_id
            WHERE v.id = source_concepts.video_id
              AND uc.user_id = auth.uid()
        )
    );

CREATE POLICY source_edges_select ON source_edges
    FOR SELECT USING (
        video_id IS NULL OR EXISTS (
            SELECT 1
            FROM videos v
            JOIN user_channels uc ON uc.channel_id = v.channel_id
            WHERE v.id = source_edges.video_id
              AND uc.user_id = auth.uid()
        )
    );

CREATE POLICY knowledge_artifacts_select ON knowledge_artifacts
    FOR SELECT USING (
        user_id = auth.uid()
        OR (
            user_id IS NULL
            AND (
                video_id IS NULL OR EXISTS (
                    SELECT 1
                    FROM videos v
                    JOIN user_channels uc ON uc.channel_id = v.channel_id
                    WHERE v.id = knowledge_artifacts.video_id
                      AND uc.user_id = auth.uid()
                )
            )
        )
    );

CREATE POLICY agent_notes_select ON agent_notes
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY agent_notes_insert ON agent_notes
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY agent_notes_update ON agent_notes
    FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY agent_notes_delete ON agent_notes
    FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY personal_concepts_select ON personal_concepts
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY personal_concepts_insert ON personal_concepts
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY personal_concepts_update ON personal_concepts
    FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY personal_concepts_delete ON personal_concepts
    FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY personal_context_links_select ON personal_context_links
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY personal_context_links_insert ON personal_context_links
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY personal_context_links_delete ON personal_context_links
    FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY context_preferences_select ON context_preferences
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY context_preferences_insert ON context_preferences
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY context_preferences_update ON context_preferences
    FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY context_preferences_delete ON context_preferences
    FOR DELETE USING (auth.uid() = user_id);
