// One-off dev E2E: index a video through the real UI, then search it.
import { chromium } from 'playwright';

const URL = 'http://localhost:5173';
const VIDEO = 'https://www.youtube.com/watch?v=arj7oStGLkU'; // Tim Urban TED talk, captioned, ~14min
const QUERY = 'what does he say about the panic monster waking up';

const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
page.on('console', (m) => m.type() === 'error' && console.log('[console.error]', m.text()));

await page.goto(URL, { waitUntil: 'networkidle' });

// 1. Index the video
await page.getByLabel(/Paste source and optional query/i).fill(VIDEO);
await page.waitForTimeout(300);
await page.getByRole('button', { name: 'Add context', exact: true }).last().click();
console.log('indexing started...');
await page.screenshot({ path: 'screenshots/e2e-1-indexing.png' });

// Wait until the app navigates to library (onIndexComplete) — up to 4 min
await page
  .getByText(/Video context library|library is empty/i)
  .first()
  .waitFor({ timeout: 240_000 });
await page.waitForTimeout(1500);
await page.screenshot({ path: 'screenshots/e2e-2-library.png', fullPage: true });
console.log('index complete, library shown');

// 2. Search the library
await page.getByRole('button', { name: 'Dashboard', exact: true }).click();
await page.waitForTimeout(600);
await page.getByRole('button', { name: 'Search library' }).first().click(); // mode toggle card
await page.getByLabel('Describe the context').fill(QUERY);
await page.getByRole('button', { name: 'Search library', exact: true }).last().click();
console.log('search started...');

// Wait for results view (video player card appears)
await page.getByText('New Search').waitFor({ timeout: 120_000 });
await page.waitForTimeout(2500);
await page.screenshot({ path: 'screenshots/e2e-3-results.png', fullPage: true });
const clips = await page.locator('h3:text-is("Clips")').count();
console.log('results rendered, clips sidebar present:', clips > 0);

// Cited answer card (generated by backend/answers.py)
const answerCard = await page.getByText('Answer with receipts').count();
console.log('answer card present:', answerCard > 0);
const citationChips = await page.locator('p button:has(svg)').count();
console.log('citation chips:', citationChips);

await browser.close();
console.log('E2E DONE');
